services:
  tt-redis:
    image: redis:latest
    container_name: tt-redis
    ports:
      - "8004:6379"
    volumes:
      - ./redis-data:/data
    restart: unless-stopped
    # translate to command
    # docker start --name tt-redis -p 8004:8004 -v redis-data:/data --restart unless-stopped redis:latest
  tt-mongo:
    image: mongo:latest
    container_name: tt-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    restart: unless-stopped
    # translate to command
    # docker start --name tt-mongo -p 27017:27017 -v mongo-data:/data/db --restart unless-stopped mongo:latest
